manjaresdelbeagle/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rotiseria.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rotiseria/urls.py
from django.urls import path 
from rotiseria.View.Administrador import CrearProducto, ListarProducto, BorrarProducto,editarProducto, CrearCategoria, ListarCategorias, BorrarCategoría, index, indexAdministrador, editarcategoria, locales 
from rotiseria.View.Recepcionista import CrearBloque, ListarBloque, BorrarBloque, ListarPedido, pedidosConfirmados, confirmar_pedido, rechazar_pedido, pedidosRechazados, pedidosListos, añadir_bloque, enviar_repartidor, nuevo_bloque, pedido_entregado, historial_pedidos 
from rotiseria.View.Cliente import CrearCliente, ListarCliente, BorrarCliente, CrearPedido, indexCliente, quienesSomos, contacto 
from rotiseria.View.Repartidor import ListarDatosMapa, entregar_pedido 
from rotiseria.View.Sesion import SignIn, register, login 
from rotiseria.View.Carrito import VistaCarrito 
from django.contrib.auth.views import logout_then_login

urlpatterns = [
path('indexAdministrador',indexAdministrador, name = 'index_administrador'),
path('locales', locales, name = 'locales'),
path('editarProducto/<int:id_producto>', editarProducto, name = 'editar_producto'),
path('crear_Producto',CrearProducto.as_view(), name = 'crear_producto'),
path('listarProductos',ListarProducto.as_view(), name = 'listar_producto'),
path('borrarProducto/<str:nombrep>/', BorrarProducto, name='borrar_producto'),

path('editarCategoría/<str:nombre>', editarcategoria, name = 'editar_categoria'),
path('crearCategoría',CrearCategoria.as_view(), name = 'crear_categoria'),
path('listarCategorías',ListarCategorias.as_view(), name = 'listar_categoria'),
path('borrarCategoría/<str:nombrec>/', BorrarCategoría, name='borrar_categoria'),

path('crearBloque',CrearBloque.as_view(), name = 'crear_bloque'),
path('listarBloques',ListarBloque.as_view(), name = 'listar_bloque'),
path('borrarBloque/<int:id>/', BorrarBloque, name='borrar_bloque'),

path('crearCliente',CrearCliente.as_view(), name = 'crear_cliente'),
path('listarClientes',ListarCliente.as_view(), name = 'listar_cliente'),
path('borrarCliente/<int:dni>/', BorrarCliente, name='borrar_cliente'),

path('', indexCliente, name='indexCliente'),
path('indexUsuario', index, name = "indexUsuario"),
path('crearPedido',CrearPedido.as_view(), name = 'crear_pedido'),

path('quienesSomos',quienesSomos, name = 'quienesSomos'),
path('contacto',contacto, name = 'contacto'),

# Urls del recepcionista
path('recepcionista',ListarPedido.as_view(), name = 'recepcionista'),
path('pedidosConfirmados', pedidosConfirmados, name = 'pedidos_confirmados'),
path('pedidosRechazados', pedidosRechazados, name = 'pedidos_rechazados'),
path('pedidosListos', pedidosListos, name = 'pedidos_listos'),
path('añadir_bloque/<int:id>/', añadir_bloque, name = 'añadir_bloque'),
path('confirmar_pedido/<int:id>/', confirmar_pedido, name = 'confirmar_pedido'),
path('rechazar_pedido/<int:id>/', rechazar_pedido, name = 'rechazar_pedido'),
path('enviar_repartidor', enviar_repartidor, name = 'enviar_repartidor'),
path('nuevo_bloque', nuevo_bloque, name = 'nuevo_bloque'),
path('pedido_entregado/<int:id>/', pedido_entregado, name='pedido_entregado'),
path('historial_pedidos', historial_pedidos, name='historial_pedidos'),

path('quienesSomos',quienesSomos, name = 'quienesSomos'),

#repartidor
path('repartidor',ListarDatosMapa.as_view(), name = 'listar_datos_mapa'),
path('entregar_pedido/<int:id_pedido>/',entregar_pedido, name = 'entregar_pedido'),

#iniciar sesion
path('accounts/login/',login, name = 'login'),
#cerrar sesion
path('logout/',logout_then_login, name = 'logout'),
path('registro',register, name = 'registro'),

#URLs para operar con el carrito de compras
path('carrito', VistaCarrito.obtenerCarrito, name = "carrito"),
path('agregaritem', VistaCarrito.agregarItem, name = "agregaritem"),
path('eliminarItem', VistaCarrito.eliminarItem, name = "eliminarItem"),
path('confirmarPedido', VistaCarrito.confirmarPedido, name = "confirmarPedido"),
]

rotiseria/models/producto.py
from django.db import models
from rotiseria.models.categoría import Categoría

class Producto(models.Model):
    
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=50, blank=True)
    foto = models.ImageField(upload_to="rotiseria/images/", null=True)
    precioActual = models.DecimalField(max_digits=8, decimal_places=2)
    categoria= models.ForeignKey(Categoría, on_delete=models.CASCADE)
    ganancia= models.IntegerField(null=True)

    def __str__(self):
        return self.nombre

    def getPrecioActual(self):
        return self.precioActual

rotiseria/models/rol.py
from django.db import models

class Rol (models.Model):
    nombre = models.CharField (max_length=15)

    def __str__(self):
        return self.nombre

rotiseria/forms.py
from django import forms
from .models import Producto, Categoría, Cliente, Bloque, Pedido, Rol, Usuario
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ProductoForm(forms.ModelForm):

	class Meta:
		model = Producto

		fields = [
			'nombre',
			'descripcion',
            'foto',
            'precioActual',
			'categoria',
			'ganancia',
		]
		labels = {
			'nombre': 'Nombre',
			'descripcion': 'Descripcion',
            'foto': 'Foto',
            'precioActual': 'Precio Actual',
			'categoria':'Categoria',
		    'ganancia': 'Ganancia',
		}



class CategoriaForm (forms.ModelForm):
	class Meta:
		model = Categoría

		fields = [
			'nombre',

		]
		labels = {
			'nombre': 'Nombre'}


class BloqueForm(forms.ModelForm):
	class Meta:
		model = Bloque

		fields = [
			'id',
			'fecha'		
		]

		labels = {
			'id': 'ID',
			'fecha': 'Fecha',
			}



class ClienteForm(forms.ModelForm):
	class Meta:
		model = Cliente

		fields = [

			'nombre',
			'telefono',

		]
		labels = {
			'nombre': 'Nombre',
			'telefono': 'Telefono',}


class PedidoForm(forms.ModelForm):
	class Meta:
		model = Pedido
		fields = [
			'fecha',
			'total',
			'productos',
			'bloque',
			'estadoPedido',
		]
		labels = {
			'fecha': 'Fecha',
			'total': 'Total',
			'productos':'Productos',
			'bloque': 'Bloque',
			'estadoPedido': 'EstadoPedido'}


class RegistroForm(UserCreationForm):

	rol = forms.CharField(required=True)
	class Meta:
			model = User
			fields = [
				'username',
				'first_name',
				'last_name',
				'password1',
				'password2',
				'rol'
			]



	def save (self, commit=True):
		user = super(RegistroForm,self).save(commit=False)
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.rol = self.cleaned_data['rol']

		if commit:
			user.save()

		return user


class PedidoAlimentoForm(forms.Form):

    alimento = forms.IntegerField()
    cantidad = forms.IntegerField()

class ProductoIDForm(forms.Form):

    alimento = forms.IntegerField()

class DatosClienteForm(forms.Form):

	nombreApellido = forms.CharField()
	celular = forms.IntegerField()
	descripcion = forms.CharField()
	direccion = forms.CharField()
	latitud = forms.CharField()
	longitud = forms.CharField()
	pago = forms.CharField()

class UserForm(UserCreationForm):

	rol = forms.ModelChoiceField(
		queryset = Rol.objects.all(),
		required = True,
	)

	class Meta:
		model = User
		fields = ['username',
				  'password1',
				  'password2']

templates/Administrador/borrarcategoría.html
{% extends 'Layouts/baseUsuarios.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
  <title>Eliminar {{categoría.nombre}}</title>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12" style="text-align: center">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h3>¿Desea eliminar la categoría <b>"{{categoría.nombre}}"</b>?</h3>
                    <button class="btn btn-danger" type="submit">Si, eliminar</button>
                    <a class="btn btn-primary" href="{% url 'listar_categoria' %}">Cancelar</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/Administrador/borrarproducto.html
{% extends 'Layouts/baseUsuarios.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
  <title>Eliminar {{producto.nombre}}</title>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12" style="text-align: center">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h3>¿Desea eliminar el producto <b>"{{producto.nombre}}"</b>?</h3>
                    <button class="btn btn-danger" type=" submit">Si, eliminar</button>
                    <a class="btn btn-success" href="{% url 'listar_producto' %}">Cancelar</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/Administrador/crearcategoria.html
{% extends 'Layouts/baseUsuarios.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
  <title>Crear categoría</title>
{% endblock %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <form method = "post" enctype="multipart/form-data">
          {% csrf_token %}<br>
            <div id="div_id_nombre" class="form-group">
              <label for="id_nombre" class=" requiredField">Nombre de la categoría</label>
              <div class="">
                <input type="text" name="nombre" maxlength="50" class="textinput textInput form-control" required id="id_nombre">
              </div>
            </div>
            <button class="btn btn-success" type="submit">Guardar</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/Administrador/crearproducto.html
{% extends 'Layouts/baseUsuarios.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
  <title>Inicio</title>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6" >
                <form method = "post" enctype="multipart/form-data">
                    {% csrf_token %}
                   
                    <div id="div_id_nombre" class="form-group">
                        <label for="id_nombre" class=" requiredField">Nombre</label>
                        <input type="text" name="nombre" maxlength="50" class="textinput textInput form-control" required id="id_nombre">
                    </div>
                    <div id="div_id_descripcion" class="form-group">
                        <label for="id_descripcion" class="">Descripcion</label>
                        <input type="text" name="descripcion" maxlength="50" class="textinput textInput form-control" id="id_descripcion">
                    </div>
                    <div id="div_id_foto" class="form-group">
                        <label for="id_foto" class=" requiredField">Foto</label>
                        <input type="file" name="foto" accept="image/*" class="clearablefileinput form-control" required id="id_foto">
                    </div>
                    <div id="div_id_precioActual" class="form-group">
                        <label for="id_precioActual" class=" requiredField">Precio Actual</label>
                        <input type="number" name="precioActual" step="0.001" class="numberinput form-control" required id="id_precioActual">
                    </div>
                    <div>Categoria</div>
                    <select name="categoria" id="id_categoria">
                        {% for item in categorias %}
                            <option value="{{item.pk}}">{{item.nombre}}</option>
                        {% endfor %}
                    </select>
                    <div id="div_id_ganancia" class="form-group">
                        <label for="id_ganancia" class=" requiredField">Ganancia</label>
                        <input type="number" name="ganancia" class="numberinput form-control" required id="id_ganancia">
                    </div>
                    <button type="submit" class="btn btn-success">Guardar</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/Administrador/editarProducto.html
{% extends 'Layouts/baseUsuarios.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
  <title>Editar {{producto.nombre}}</title>
{% endblock %}
{% block content %}
    <form method="post">
    {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <a href="{% url 'listar_producto' %}" class="btn btn-success">Atrás</a> <br>
                    <div id="div_id_nombre" class="form-group">
                        <label for="id_nombre" class=" requiredField">Nombre</label>
                        <input type="text" name="nombre" value='{{producto.nombre}}' maxlength="50" class="textinput textInput form-control" required id="id_nombre">
                    </div>
                    <div id="div_id_descripcion" class="form-group">
                        <label for="id_descripcion" class="">Descripcion</label>
                        <input type="text" name="descripcion" value="Con papas" maxlength="50" class="textinput textInput form-control" id="id_descripcion">
                    </div>
                    <div id="div_id_foto" class="form-group">
                        <label for="id_foto" class=" requiredField">Imagen</label><br>
                        <img class="card-img-top" src="/media/{{producto.foto}}/" alt="Card image cap" width="100" height="200">
                        <br> Modificar:
                        <input type="file" name="foto" accept="image/*" class="clearablefileinput form-control" id="id_foto">
                    </div>
                    <div id="div_id_precioActual" class="form-group">
                        <label for="id_precioActual" class=" requiredField">Precio Actual</label>
                        <input type="text" name="precioActual" value={{producto.precioActual}} class="numberinput form-control" required id="id_precioActual">
                    </div>
                    <div id="div_id_categoria" class="form-group">
                        <label for="id_categoria" class=" requiredField">Categoria</label>
                        <select name="categoria" class="select form-control" required id="id_categoria">
                            {% for categoria in categorias %}
                                <option value="{{categoria.pk}}">{{categoria.nombre}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div id="div_id_ganancia" class="form-group">
                        <label for="id_ganancia" class=" requiredField">Ganancia</label>
                        <input type="text" name="ganancia" value={{producto.ganancia}} class="numberinput form-control" required id="id_ganancia">
                    </div>
                    <input class="btn btn-success" value="Modificar" onclick="cambiarNumeros()" type="submit">
                </div>
            </div>
        </div>
    </form>

    <script>
        function cambiarNumeros() {
            //precio actual
            var precio = document.getElementById('id_precioActual').value;
            var precioReal = "";
            for (var i=0; i<precio.length; i++){
                if (precio[i] == ",") {
                    precioReal = precioReal + ".";
                } else {
                    precioReal = precioReal + precio[i];
                }
            }
            document.getElementById('id_precioActual').value = precioReal;

            //ganancia
            precioReal = "";
            var ganancia = document.getElementById('id_ganancia').value;
            for (var i=0; i<ganancia.length; i++){
                if (ganancia[i] == ",") {
                    precioReal = precioReal + ".";
                } else {
                    precioReal = precioReal + precio[i];
                }
            }
            document.getElementById('id_ganancia').value = precioReal;
        }
    </script>
{% endblock %}

templates/Administrador/editarcategoria.html
{% extends 'Layouts/baseUsuarios.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
  <title>Editar {{categoria.nombre}}</title>
{% endblock %}
{% block content %}
    <form method="post">
    {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <a href="{% url 'listar_categoria' %}" class="btn btn-success">Atrás</a> <br>
                    <div id="div_id_nombre" class="form-group">
                        <label for="id_nombre" class=" requiredField">Nombre</label>
                        <input type="text" name="nombre" value='{{categoria.nombre}}' maxlength="50" class="textinput textInput form-control" required id="id_nombre">
                    </div>
                    <input class="btn btn-success" type="submit" value="Modificar">
                </div>
            </div>
        </div>
    </form>
{% endblock %}

templates/Administrador/indexAdministrador.html
{% extends 'Layouts/baseUsuarios.html'%}
{% load static %}
{% block title %}
  <title>Inicio Administrador</title>
{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-6" align="center">
      <div class="card" style="width: 16rem;">
        <img src="/media/pensando.png" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title" align="center">Categorias</h5>
          <hr style="background-color: gray;">
          <a href="{% url 'listar_categoria' %}" class="btn btn-success">Listar</a>
          <a href="{% url 'crear_categoria' %}" class="btn btn-success">Cargar</a>
        </div>
      </div>
    </div>
    <div class="col-sm-6" align="center">
      <div class="card" style="width: 16rem;">
        <img src="/media/pensando.png" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title" align="center">Productos</h5>
          <hr style="background-color: gray;">
          <a href="{% url 'listar_producto' %}" class="btn btn-success">Listar</a>
          <a href="{% url 'crear_producto' %}" class="btn btn-success">Cargar</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/Administrador/listarcategorías.html
{% extends 'Layouts/baseUsuarios.html'%}
{% load static %}
{% block title %}
  <title>Lista de Categorías</title>
{% endblock %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12" align="center">
        <table class="table table-bordered">
          <thead>
            <tr align="center">
              <td><b>Categorías</b></td>
              <td colspan="2"><b>Acciones</b></td>
            </tr>
          </thead>
          {% if categorías %}
            {% for item in categorías %}
              <tr>
                <td>{{item.nombre}}</td>
                <td align="center"><a class="btn btn-primary" href="{% url 'editar_categoria' item.nombre %}">Editar</a></td>
                <td align="center"><a class="btn btn-danger" href="{% url 'borrar_categoria' item.nombre %}">Eliminar</a></td>
              </tr>
            {% endfor %}
        </table>
          {% else %}
            <h1>No hay registro de categorías</h1>
          {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

templates/Administrador/listarproducto.html
{% extends 'Layouts/baseUsuarios.html'%}
{% load static %}
{% block title %}
    <title>Lista de Productos</title>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12" align="center">
                <table class="table table-bordered">
                    <thead>
                        <tr align="center">
                            <td><b>Producto</b></td>
                            <td><b>Descripcion</b></td>
                            <td><b>Precio</b></td>
                            <td colspan="2"><b>Acciones</b></td>
                        </tr>
                    </thead>
                    {% if productos %}
                        {% for item in productos %}
                            <tr>
                                <td>{{item.nombre}}</td>
                                <td>{{item.descripcion}}</td>
                                <td align="center">{{item.precioActual}}</td>
                                <td align="center"><a class="btn btn-primary" href="{% url 'editar_producto' item.id %}">Editar</a></td>
                                <td align="center"><a class="btn btn-danger" href="{% url 'borrar_producto' item.nombre %}">Eliminar</a></td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <h1>No hay registros de productos</h1>
                    {% endif %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}