manjaresdelbeagle/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rotiseria.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rotiseria/urls.py
from django.urls import path 
from rotiseria.View.Administrador import CrearProducto, ListarProducto, BorrarProducto,editarProducto, CrearCategoria, ListarCategorias, BorrarCategoría, index, indexAdministrador, editarcategoria, locales 
from rotiseria.View.Recepcionista import CrearBloque, ListarBloque, BorrarBloque, ListarPedido, pedidosConfirmados, confirmar_pedido, rechazar_pedido, pedidosRechazados, pedidosListos, añadir_bloque, enviar_repartidor, nuevo_bloque, pedido_entregado, historial_pedidos 
from rotiseria.View.Cliente import CrearCliente, ListarCliente, BorrarCliente, CrearPedido, indexCliente, quienesSomos, contacto 
from rotiseria.View.Repartidor import ListarDatosMapa, entregar_pedido 
from rotiseria.View.Sesion import SignIn, register, login 
from rotiseria.View.Carrito import VistaCarrito 
from django.contrib.auth.views import logout_then_login

urlpatterns = [
path('indexAdministrador',indexAdministrador, name = 'index_administrador'),
path('locales', locales, name = 'locales'),
path('editarProducto/<int:id_producto>', editarProducto, name = 'editar_producto'),
path('crear_Producto',CrearProducto.as_view(), name = 'crear_producto'),
path('listarProductos',ListarProducto.as_view(), name = 'listar_producto'),
path('borrarProducto/<str:nombrep>/', BorrarProducto, name='borrar_producto'),

path('editarCategoría/<str:nombre>', editarcategoria, name = 'editar_categoria'),
path('crearCategoría',CrearCategoria.as_view(), name = 'crear_categoria'),
path('listarCategorías',ListarCategorias.as_view(), name = 'listar_categoria'),
path('borrarCategoría/<str:nombrec>/', BorrarCategoría, name='borrar_categoria'),

path('crearBloque',CrearBloque.as_view(), name = 'crear_bloque'),
path('listarBloques',ListarBloque.as_view(), name = 'listar_bloque'),
path('borrarBloque/<int:id>/', BorrarBloque, name='borrar_bloque'),

path('crearCliente',CrearCliente.as_view(), name = 'crear_cliente'),
path('listarClientes',ListarCliente.as_view(), name = 'listar_cliente'),
path('borrarCliente/<int:dni>/', BorrarCliente, name='borrar_cliente'),

path('', indexCliente, name='indexCliente'),
path('indexUsuario', index, name = "indexUsuario"),
path('crearPedido',CrearPedido.as_view(), name = 'crear_pedido'),

path('quienesSomos',quienesSomos, name = 'quienesSomos'),
path('contacto',contacto, name = 'contacto'),

# Urls del recepcionista
path('recepcionista',ListarPedido.as_view(), name = 'recepcionista'),
path('pedidosConfirmados', pedidosConfirmados, name = 'pedidos_confirmados'),
path('pedidosRechazados', pedidosRechazados, name = 'pedidos_rechazados'),
path('pedidosListos', pedidosListos, name = 'pedidos_listos'),
path('añadir_bloque/<int:id>/', añadir_bloque, name = 'añadir_bloque'),
path('confirmar_pedido/<int:id>/', confirmar_pedido, name = 'confirmar_pedido'),
path('rechazar_pedido/<int:id>/', rechazar_pedido, name = 'rechazar_pedido'),
path('enviar_repartidor', enviar_repartidor, name = 'enviar_repartidor'),
path('nuevo_bloque', nuevo_bloque, name = 'nuevo_bloque'),
path('pedido_entregado/<int:id>/', pedido_entregado, name='pedido_entregado'),
path('historial_pedidos', historial_pedidos, name='historial_pedidos'),

path('quienesSomos',quienesSomos, name = 'quienesSomos'),

#repartidor
path('repartidor',ListarDatosMapa.as_view(), name = 'listar_datos_mapa'),
path('entregar_pedido/<int:id_pedido>/',entregar_pedido, name = 'entregar_pedido'),

#iniciar sesion
path('accounts/login/',login, name = 'login'),
#cerrar sesion
path('logout/',logout_then_login, name = 'logout'),
path('registro',register, name = 'registro'),

#URLs para operar con el carrito de compras
path('carrito', VistaCarrito.obtenerCarrito, name = "carrito"),
path('agregaritem', VistaCarrito.agregarItem, name = "agregaritem"),
path('eliminarItem', VistaCarrito.eliminarItem, name = "eliminarItem"),
path('confirmarPedido', VistaCarrito.confirmarPedido, name = "confirmarPedido"),
]

rotiseria/forms.py
from django import forms
from .models import Producto, Categoría, Cliente, Bloque, Pedido, Rol, Usuario
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ProductoForm(forms.ModelForm):

	class Meta:
		model = Producto

		fields = [
			'nombre',
			'descripcion',
            'foto',
            'precioActual',
			'categoria',
			'ganancia',
		]
		labels = {
			'nombre': 'Nombre',
			'descripcion': 'Descripcion',
            'foto': 'Foto',
            'precioActual': 'Precio Actual',
			'categoria':'Categoria',
		    'ganancia': 'Ganancia',
		}



class CategoriaForm (forms.ModelForm):
	class Meta:
		model = Categoría

		fields = [
			'nombre',

		]
		labels = {
			'nombre': 'Nombre'}


class BloqueForm(forms.ModelForm):
	class Meta:
		model = Bloque

		fields = [
			'id',
			'fecha'		
		]

		labels = {
			'id': 'ID',
			'fecha': 'Fecha',
			}



class ClienteForm(forms.ModelForm):
	class Meta:
		model = Cliente

		fields = [

			'nombre',
			'telefono',

		]
		labels = {
			'nombre': 'Nombre',
			'telefono': 'Telefono',}


class PedidoForm(forms.ModelForm):
	class Meta:
		model = Pedido
		fields = [
			'fecha',
			'total',
			'productos',
			'bloque',
			'estadoPedido',
		]
		labels = {
			'fecha': 'Fecha',
			'total': 'Total',
			'productos':'Productos',
			'bloque': 'Bloque',
			'estadoPedido': 'EstadoPedido'}


class RegistroForm(UserCreationForm):

	rol = forms.CharField(required=True)
	class Meta:
			model = User
			fields = [
				'username',
				'first_name',
				'last_name',
				'password1',
				'password2',
				'rol'
			]



	def save (self, commit=True):
		user = super(RegistroForm,self).save(commit=False)
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.rol = self.cleaned_data['rol']

		if commit:
			user.save()

		return user


class PedidoAlimentoForm(forms.Form):

    alimento = forms.IntegerField()
    cantidad = forms.IntegerField()

class ProductoIDForm(forms.Form):

    alimento = forms.IntegerField()

class DatosClienteForm(forms.Form):

	nombreApellido = forms.CharField()
	celular = forms.IntegerField()
	descripcion = forms.CharField()
	direccion = forms.CharField()
	latitud = forms.CharField()
	longitud = forms.CharField()
	pago = forms.CharField()

class UserForm(UserCreationForm):

	rol = forms.ModelChoiceField(
		queryset = Rol.objects.all(),
		required = True,
	)

	class Meta:
		model = User
		fields = ['username',
				  'password1',
				  'password2']

templates/Sesion/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Login</title>
    <link rel="shortcut icon" type="image/x-icon" href="/media/logo.ico" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"/>
  </head>
  <body class="text-center" style="background-image: url(/media/Textura.jpg); background-size: 100%;">
    <form class=" site-form" action="/accounts/login/" method="post">
      {% csrf_token %}
      <div class="card text-center" style="width: 30%; margin:auto auto auto auto; margin-top: 4%;">
        <div class="card-header">
          <img class="mt-4 mb-4" src="/media/DefaultPerfil.png" width="40%" height="40%">
        </div>
        <br>
        <div class="card-body">
          <!-- E-MAIL -->
          <label class="sr-only">Usuario</label>
          <input type="text" name="username" placeholder="Usuario" autofocus class="textinput textInput form-control" required id="id_username">
          <!-- CONTRASEÑA -->
          <label  class="sr-only">Contraseña</label>
          <input type="password" name="password" placeholder="Contraseña" class="textinput textInput form-control" required id="id_password">
          <br>
          <div class="checkbox mb-3">
            <label>
              <input type="checkbox" value="remember-me"> Recordarme
            </label>
          </div>
          <!-- BOTON INICIAR SESION -->
          <button class="btn btn-lg btn-success btn-block" type="Submit">Iniciar Sesión</button>
        </div>
        <br>
        <div class="card-footer text-muted">
          <p class="mt-1 mb-1 text-muted">&copy; 2019</p>
        </div>
      </div>
    </form>
    {% block content %}
      <!-- REGISTRO -->
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/Sesion/registro.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Registro</title>
    <link rel="shortcut icon" type="image/x-icon" href="media/logo.ico" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body class="text-center" style="background-image: url(/media/Textura.jpg); background-size: 100%;">
    <form method = "post">
        {% csrf_token %}
        <div class="card text-center" style="width: 30%; margin:auto auto auto auto; margin-top: 4%;">
            <div class="card-body">
                <div id="div_id_username" class="form-group">
                    <label for="id_username" class=" requiredField" style="float: left;">Nombre de usuario:</label>
                    <div class="">
                        <input type="text" name="username" maxlength="150" autofocus class="textinput textInput form-control" required id="id_username">
                    </div>
                </div>
                <div id="div_id_password1" class="form-group">
                    <label for="id_password1" class=" requiredField" style="float: left;">Contraseña:</label>
                    <div class="">
                        <input type="password" name="password1" class="textinput textInput form-control" required id="id_password1">
                        <p>La contraseña debe contener mayusculas, minusculas y numeros.</p>
                    </div>
                </div>
                <div id="div_id_password2" class="form-group">
                    <label for="id_password2" class=" requiredField" style="float: left;">Confirmación de contraseña:</label>
                    <input type="password" name="password2" class="textinput textInput form-control" required id="id_password2">
                </div>
                <div id="div_id_rol" class="form-group">
                    <label for="id_rol" class=" requiredField" style="float: left;">Rol:</label>
                    <div class="" >
                        <select name="rol" id="id_rol">
                            {% for item in roles %}
                                <option value="{{item.id}}">{{item.nombre}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <button class="btn btn-lg btn-success btn-block" type="submit">Registrarme</button>
            </div>
        </div>
    </form>
</body>
</html>